"""add daily_number and confirmed_date to order

Revision ID: 1b1c584237f0
Revises: f093f8e07fbc
Create Date: 2026-07-10 02:38:17.578696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b1c584237f0'
down_revision = 'f093f8e07fbc'
branch_labels = None
depends_on = None


def upgrade():
    # No server_default on either column: existing rows (including ones already
    # status='Confirmed') backfill to NULL - they were confirmed before this feature
    # existed, so they never get a daily number. The UNIQUE constraint is what makes
    # the database itself enforce "no two orders share a number the same day", instead
    # of trusting the app server not to race.
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('daily_number', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_order_confirmed_date'), ['confirmed_date'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_order_confirmed_date'), ['confirmed_date', 'daily_number'])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_order_confirmed_date'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_order_confirmed_date'))
        batch_op.drop_column('daily_number')
        batch_op.drop_column('confirmed_date')

    # ### end Alembic commands ###
