"""add requested_for_tomorrow to order

Revision ID: 28c4de79fc2d
Revises: 7b29b3fece60
Create Date: 2026-07-27 21:08:54.644839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28c4de79fc2d'
down_revision = '7b29b3fece60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requested_for_tomorrow', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('requested_for_tomorrow')

    # ### end Alembic commands ###
