"""add agenda_block_minutes to user

Revision ID: 318e52fbe793
Revises: 1b1c584237f0
Create Date: 2026-07-11 03:57:15.164483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '318e52fbe793'
down_revision = '1b1c584237f0'
branch_labels = None
depends_on = None


def upgrade():
    # server_default='10' so existing users get the same default as new ones
    # (Column(..., default=10) only applies at the Python/ORM insert level, not
    # to rows already in the table before this migration runs).
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agenda_block_minutes', sa.Integer(), nullable=False,
                                       server_default='10'))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('agenda_block_minutes')

    # ### end Alembic commands ###
