"""Add BundlePromo for automatic 2x1/3x2 promotions

Revision ID: 4a8dcc91f90f
Revises: 8824ea8ecba2
Create Date: 2026-07-06 18:12:19.396501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a8dcc91f90f'
down_revision = '8824ea8ecba2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bundle_promo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('buy_quantity', sa.Integer(), nullable=False),
    sa.Column('pay_quantity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bundle_promo_product',
    sa.Column('bundle_promo_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bundle_promo_id'], ['bundle_promo.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('bundle_promo_id', 'product_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bundle_promo_product')
    op.drop_table('bundle_promo')
    # ### end Alembic commands ###
