"""Add gift-over-threshold settings to User

Revision ID: 5f6715ea6111
Revises: e679330c0804
Create Date: 2026-07-06 19:49:39.528045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f6715ea6111'
down_revision = 'e679330c0804'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gift_threshold_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('gift_product_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_gift_product_id_product', 'product', ['gift_product_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_gift_product_id_product', type_='foreignkey')
        batch_op.drop_column('gift_product_id')
        batch_op.drop_column('gift_threshold_amount')

    # ### end Alembic commands ###
