"""Add original_price to product for discount display

Revision ID: 665d3f9e5717
Revises: 7f3d9a2c5e84
Create Date: 2026-07-06 14:19:05.847712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '665d3f9e5717'
down_revision = '7f3d9a2c5e84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('original_price')

    # ### end Alembic commands ###
