"""add accept_orders_outside_hours to user

Revision ID: 735461989a34
Revises: 85b57e97d543
Create Date: 2026-07-17 17:02:38.198717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '735461989a34'
down_revision = '85b57e97d543'
branch_labels = None
depends_on = None


def upgrade():
    # server_default=false() so the existing owner row (NOT NULL, no app-side default
    # applies to an ALTER TABLE on SQLite) backfills to the safe, conservative value -
    # nobody's cart silently starts accepting out-of-hours orders on upgrade.
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accept_orders_outside_hours', sa.Boolean(),
                                       nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('accept_orders_outside_hours')

    # ### end Alembic commands ###
