"""add min_select and max_select to product_option_group

Revision ID: 7b29b3fece60
Revises: ea6f18c7c8b9
Create Date: 2026-07-26 22:26:03.442378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b29b3fece60'
down_revision = 'ea6f18c7c8b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_option_group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_select', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_select', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_option_group', schema=None) as batch_op:
        batch_op.drop_column('max_select')
        batch_op.drop_column('min_select')

    # ### end Alembic commands ###
