"""add prep_minutes to product

Revision ID: 85b57e97d543
Revises: 318e52fbe793
Create Date: 2026-07-13 23:11:58.222644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85b57e97d543'
down_revision = '318e52fbe793'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prep_minutes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('prep_minutes')

    # ### end Alembic commands ###
