"""Add banner image and show_in_banner to coupon

Revision ID: 8824ea8ecba2
Revises: d18bc5270e01
Create Date: 2026-07-06 17:09:26.933637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8824ea8ecba2'
down_revision = 'd18bc5270e01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_in_banner', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('banner_image_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupon', schema=None) as batch_op:
        batch_op.drop_column('banner_image_filename')
        batch_op.drop_column('show_in_banner')

    # ### end Alembic commands ###
