"""add payment_status to order

Revision ID: 8b61943aaffa
Revises: e8afd282d248
Create Date: 2026-07-09 13:21:36.796344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b61943aaffa'
down_revision = 'e8afd282d248'
branch_labels = None
depends_on = None


def upgrade():
    # server_default='pending' so existing orders backfill to "payment unknown" -
    # we never assert an old order was paid when we don't actually know that.
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_status', sa.String(length=10), nullable=False,
                                       server_default='pending'))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('payment_status')

    # ### end Alembic commands ###
