"""montos CLP como enteros

Revision ID: a222c27e8aed
Revises: 5f6715ea6111
Create Date: 2026-07-08 05:00:19.450494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a222c27e8aed'
down_revision = '5f6715ea6111'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_radius_tier', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('delivery_zone', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('shipping_cost',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('total_price',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('discount_amount',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('bundle_discount_amount',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('cash_amount',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('order_item_option', schema=None) as batch_op:
        batch_op.alter_column('price_delta',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('original_price',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)

    with op.batch_alter_table('product_option', schema=None) as batch_op:
        batch_op.alter_column('price_delta',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('min_delivery_order',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('gift_threshold_amount',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('gift_threshold_amount',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('min_delivery_order',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('product_option', schema=None) as batch_op:
        batch_op.alter_column('price_delta',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('original_price',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('order_item_option', schema=None) as batch_op:
        batch_op.alter_column('price_delta',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('cash_amount',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('bundle_discount_amount',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('discount_amount',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('total_price',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('shipping_cost',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('delivery_zone', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('delivery_radius_tier', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
