"""add onboarding_checklist_dismissed to user

Revision ID: b50571c314fb
Revises: 735461989a34
Create Date: 2026-07-21 04:03:09.847885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b50571c314fb'
down_revision = '735461989a34'
branch_labels = None
depends_on = None


def upgrade():
    # server_default=false() so the existing owner row (NOT NULL, no app-side default
    # applies to an ALTER TABLE on SQLite) backfills to the safe value - the checklist
    # shows up for everyone already installed, same as a brand new install would see.
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('onboarding_checklist_dismissed', sa.Boolean(),
                                       nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('onboarding_checklist_dismissed')

    # ### end Alembic commands ###
