"""unique constraints on category name and subcategory name+category

Revision ID: d10baf81c6af
Revises: 28c4de79fc2d
Create Date: 2026-07-30 23:21:33.067536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd10baf81c6af'
down_revision = '28c4de79fc2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_category_name'), ['name'])

    with op.batch_alter_table('subcategory', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_subcategory_name'), ['name', 'category_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subcategory', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_subcategory_name'), type_='unique')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_category_name'), type_='unique')

    # ### end Alembic commands ###
