"""Add coupon system (Coupon, CouponRedemption, Order.coupon/discount)

Revision ID: d18bc5270e01
Revises: 665d3f9e5717
Create Date: 2026-07-06 15:03:47.626429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd18bc5270e01'
down_revision = '665d3f9e5717'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('discount_percent', sa.Float(), nullable=False),
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.Column('max_total_uses', sa.Integer(), nullable=True),
    sa.Column('max_uses_per_customer', sa.Integer(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('coupon_redemption',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coupon_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('phone_digits', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupon.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coupon_product',
    sa.Column('coupon_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupon.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('coupon_id', 'product_id')
    )
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coupon_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('discount_amount', sa.Float(), nullable=False, server_default='0'))
        batch_op.create_foreign_key('fk_order_coupon_id_coupon', 'coupon', ['coupon_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint('fk_order_coupon_id_coupon', type_='foreignkey')
        batch_op.drop_column('discount_amount')
        batch_op.drop_column('coupon_id')

    op.drop_table('coupon_product')
    op.drop_table('coupon_redemption')
    op.drop_table('coupon')
    # ### end Alembic commands ###
