"""Add Order.bundle_discount_amount

Revision ID: e679330c0804
Revises: 4a8dcc91f90f
Create Date: 2026-07-06 18:13:37.940295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e679330c0804'
down_revision = '4a8dcc91f90f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bundle_discount_amount', sa.Float(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('bundle_discount_amount')

    # ### end Alembic commands ###
