"""add applies_to_shipping to coupon

Revision ID: e8afd282d248
Revises: c1d4f7a9b2e6
Create Date: 2026-07-08 23:18:28.674193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8afd282d248'
down_revision = 'c1d4f7a9b2e6'
branch_labels = None
depends_on = None


def upgrade():
    # server_default='0' so the 2 existing coupon rows get False (no coupon today
    # discounts shipping - matches the new, safer default for future coupons too).
    with op.batch_alter_table('coupon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('applies_to_shipping', sa.Boolean(), nullable=False,
                                       server_default=sa.text('0')))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupon', schema=None) as batch_op:
        batch_op.drop_column('applies_to_shipping')

    # ### end Alembic commands ###
