"""add is_default to product_option

Revision ID: ea6f18c7c8b9
Revises: b50571c314fb
Create Date: 2026-07-25 22:03:55.180335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea6f18c7c8b9'
down_revision = 'b50571c314fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_option', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_default', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_option', schema=None) as batch_op:
        batch_op.drop_column('is_default')

    # ### end Alembic commands ###
