"""add confirmed_at to order

Revision ID: f093f8e07fbc
Revises: 8b61943aaffa
Create Date: 2026-07-09 15:56:04.608964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f093f8e07fbc'
down_revision = '8b61943aaffa'
branch_labels = None
depends_on = None


def upgrade():
    # No server_default: existing rows (including ones already status='Confirmed')
    # backfill to NULL - we don't know when they were actually confirmed, and
    # inventing that date from created_at would misrepresent history.
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed_at', sa.DateTime(), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('confirmed_at')

    # ### end Alembic commands ###
